// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtdC170s25M7WiXgW_z1whZR_BSQkvSyE',
    appId: '1:458636555335:web:c72063de259888f5f7ed62',
    messagingSenderId: '458636555335',
    projectId: 'vital-help',
    authDomain: 'vital-help.firebaseapp.com',
    storageBucket: 'vital-help.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNyzQptH8N2EekyKK2DDbIjyjkyhAqmg',
    appId: '1:458636555335:android:95400f6833fa44fbf7ed62',
    messagingSenderId: '458636555335',
    projectId: 'vital-help',
    storageBucket: 'vital-help.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOrmpcL0mVvY3PiWJX51YkelrlMlYewko',
    appId: '1:458636555335:ios:c3586ff24bb603fbf7ed62',
    messagingSenderId: '458636555335',
    projectId: 'vital-help',
    storageBucket: 'vital-help.appspot.com',
    iosClientId: '458636555335-cqssqlbtr4u4gi0c3i533jbg86ds0lr5.apps.googleusercontent.com',
    iosBundleId: 'com.vitalhelp.user-app',
  );
}
